Increase resps folder coverage
AvitalFineRedis/jedis pull request #1
Opened 2021-12-26 16:43 UTC by AvitalFineRedis

2021-12-26 20:38 UTC, sazzad16 requested changes

2021-12-26 20:38 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/resps/RespsTest.java
> +public class RespsTest {
ResponsesToStringTest

2021-12-26 20:38 UTC, sazzad16 commented on src/test/java/redis/clients/jedis/resps/RespsTest.java
> +    public void TupleTest() {
There should be an existing TupleTest class. If that class covers this method, delete this. If not, move this there.

2021-12-27 07:14 UTC, AvitalFineRedis commented on src/test/java/redis/clients/jedis/resps/TupleTest.java
> +  public void compareSameObject() {
This test was added

2021-12-27 07:14 UTC, AvitalFineRedis commented on src/test/java/redis/clients/jedis/resps/TupleTest.java
> +  public void compareDifferentType() {
This test was added

2021-12-27 07:14 UTC, AvitalFineRedis commented on src/test/java/redis/clients/jedis/resps/TupleTest.java
> +  public void testToString() {
This test was added

2021-12-27 08:35 UTC, sazzad16 approved these changes

2021-12-27 09:25 UTC, merged